# Generated by Django 5.1.4 on 2024-12-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_payment_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='typeplan',
            name='client',
        ),
        migrations.AddField(
            model_name='payment',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
